### ISSUE TITLE
Why remove the Manjaro distro?

### ISSUE THREAD

**Issue by iboB** [sileshn/ArchWSL2#1]
Hi and thanks for the Arch and EndeavourOS on WSL distros. Awesome job!

I noticed that you removed the Manjaro repo. I also noticed the "Fuck Manjaro" commit in this one when switching to plain Arch.

I'm not here to argue against your decision, but I'm curious about it. Can you share your reasoning for it? If there are some issues with Manjaro, perhaps it is time for me to switch to Endeavour. I have been eyeing it for some time.

**Comment by sileshn** [comment]
https://github.com/sirredbeard/Awesome-WSL/pull/77
