### ISSUE TITLE
after install archwsl2,i can use it to work untill i reboot it,now i can not open it because of rebooting

### ISSUE THREAD

**Issue by ruchid123123** [sileshn/ArchWSL2#10]
### Requirements

- [X] Yes
- [ ] No

### CPU Architecture

- [ ] arm64
- [X] x64

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Version

Microsoft Windows [版本 10.0.19045.4239]

### Repro Steps

after install archwsl2,i can use it to work untill i reboot it,now i can not open it because of rebooting

### Expected Behavior

after install archwsl2,i can use it to work untill i reboot it,now i can not open it because of rebooting

### Actual Behavior

after install archwsl2,i can use it to work untill i reboot it,now i can not open it because of rebooting

**Comment by ruchid123123** [comment]
@sileshn

**Comment by sileshn** [comment]
After reboot, ArchWSL2 doesn't run. Is that what you are infering?

**Comment by ruchid123123** [comment]
> 重新启动后，ArchWSL2 不会运行。这就是你所推断的吗？

yes,could you help me to solve this problem? thanks!

**Comment by sileshn** [comment]
I could if you provide me with more details like an error msg, a video or a log as I cannot reproduce this from my end.

**Comment by ruchid123123** [comment]
> 如果您向我提供更多详细信息（例如错误消息、视频或日志），我可以，因为我无法从我这边重现此内容。

i tried to uninstall and install it again.

**Comment by ruchid123123** [comment]
> 如果您向我提供更多详细信息（例如错误消息、视频或日志），我可以，因为我无法从我这边重现这一点。

thanks a lot，i updated my system to windows 11 23h2 , now there is no problem with my wsl 2.

**Comment by sileshn** [comment]
Good to know that your issue is solved.
