### ISSUE TITLE
man - No manual entry for {anything}

### ISSUE THREAD

**Issue by acorreya** [sileshn/ArchWSL2#2]
There was no `man` by default and I tried installing `man-db`, `man-pages`, et al. manually. Even though these install, there is no `/usr/share/man` folder hence `No manual entry for {anything}`. Am I missing something?

**Comment by sileshn** [comment]
https://bbs.archlinux.org/viewtopic.php?id=255015

Then set your MANPATH and reinstall man-pages. I'll fix this in the next release

![Screenshot 2022-09-27 122637](https://user-images.githubusercontent.com/977360/192455101-97692093-975f-4800-aada-8efb99a2f5a5.png)
