### ISSUE TITLE
getpwuid failed

### ISSUE THREAD

**Issue by kovan** [sileshn/ArchWSL2#6]
### Requirements

- [X] Yes
- [ ] No

### CPU Architecture

- [ ] arm64
- [ ] x64

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Version

Microsoft Windows [Version 10.0.22621.1992]

### Repro Steps

Run Arch.exe

### Expected Behavior

Install

### Actual Behavior

$ wsl -d Arch
```
<3>WSL (8) ERROR: CreateProcessParseCommon:756: getpwuid(0) failed 2
Processing fstab with mount -a failed.

<3>WSL (8) ERROR: CreateProcessEntryCommon:324: getpwuid(0) failed 2
<3>WSL (8) ERROR: CreateProcessEntryCommon:504: execvpe /bin/sh failed 2
<3>WSL (8) ERROR: CreateProcessEntryCommon:507: Create process not expected to return
```

**Comment by sileshn** [comment]
Don't know what happens on your end, but it runs just fine on my windows 11 22621.2066.


https://github.com/sileshn/ArchWSL2/assets/977360/9ab7001a-500d-4a99-bf3d-82cd1cb3b8a4

**Comment by kovan** [comment]
Yeah yesterday I installed it sucessfully in another computer, I don't know what's up with this one

**Comment by sileshn** [comment]
You can try setting Arch as default

**Comment by kovan** [comment]
Yeah I tried that with no luck, ended up installing Manjaro.
