### ISSUE TITLE
Sources for Arch.exe?

### ISSUE THREAD

**Issue by kovan** [sileshn/ArchWSL2#7]
### Requirements

- [X] Yes
- [X] No

### CPU Architecture

- [X] arm64
- [X] x64

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Version

1

### Repro Steps

I don't like the idea of running executables that are not open source.

Could you please upload the source code for Arch.exe?

Thank you very much.

### Expected Behavior

-

### Actual Behavior

-

**Comment by sileshn** [comment]
Why don't you read the readme? The first line says, its based on [wsldl](https://github.com/yuk7/wsldl).
