### ISSUE TITLE
0x80073d05 when reinstall application.

### ISSUE THREAD

**Issue by saintedlittle** [sileshn/ArchWSL2#8]
### Requirements

- [X] Yes
- [ ] No

### CPU Architecture

- [ ] arm64
- [X] x64

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Version

Microsoft Windows [Version 10.0.22621.1992]

### Kernel Version

5.15.90.1

### Repro Steps

After reinstalling the APPX file, 
ArchWSL-AppX returns 0x80073d05 when installing the application.

### Expected Behavior

normal installation of the application.

### Actual Behavior

![изображение](https://github.com/sileshn/ArchWSL2/assets/54007979/e444a80d-a557-4f51-b7a4-82a3a36c3c23)

**Comment by sileshn** [comment]
What appx file? I haven't provided one. I think you are referring to yuk7's https://github.com/yuk7/ArchWSL repo.

**Comment by saintedlittle** [comment]
Ah, sorry.
