### ISSUE TITLE
强制重新启动之后无法打开了。

### ISSUE THREAD

**Issue by ruchid123123** [sileshn/ArchWSL2#9]
### Requirements

- [X] Yes
- [ ] No

### CPU Architecture

- [ ] arm64
- [X] x64

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Version

Microsoft Windows [版本 10.0.19045.4239]

### Repro Steps

强制重启后无法运行

### Expected Behavior

希望可以继续使用

### Actual Behavior

在使用rarcrack的时候，对windows机器进行了重启操作，导致再次启动后无法运行arch的exe程序了。

**Comment by sileshn** [comment]
I don't understand what you are trying to say even after using google translate.
